services:
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    restart: unless-stopped
    environment:
      - ASR_MODEL=medium
      - ASR_ENGINE=openai_whisper
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  converter:
    build: .
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - whisper
  